#!/usr/bin/env bash
set -euo pipefail

# Coturn TURN 서버 설치 및 설정 스크립트
# Ubuntu/Debian 서버에서 실행

echo "== Coturn TURN 서버 설치 및 설정 =="

# 1. Coturn 설치
if ! command -v turnserver &> /dev/null; then
  echo "→ Coturn 설치 중..."
  apt-get update
  apt-get install -y coturn
else
  echo "✅ Coturn이 이미 설치되어 있습니다"
fi

# 2. Coturn 설정 파일 생성
TURN_CONFIG="/etc/turnserver.conf"
TURN_USERNAME="pnt_turn_user"
TURN_PASSWORD=$(openssl rand -hex 16)

echo "→ TURN 서버 설정 파일 생성 중..."

# 기존 설정 백업
if [ -f "$TURN_CONFIG" ]; then
  cp "$TURN_CONFIG" "${TURN_CONFIG}.backup.$(date +%Y%m%d_%H%M%S)"
fi

# 설정 파일 생성
tee "$TURN_CONFIG" > /dev/null <<EOF
# PNT TURN Server Configuration
# Generated by setup-turn-server.sh

# 리스닝 포트
listening-port=3478
tls-listening-port=5349

# 외부 IP (서버의 공인 IP로 변경 필요)
# external-ip=YOUR_PUBLIC_IP

# 릴레이 IP (컨테이너/서버 환경에서는 CIDR 미지원 오류가 날 수 있어 단일 IP만 사용)
# 필요 시 서버의 실제 내부 IP로 변경하세요.
relay-ip=127.0.0.1

# 리스닝 IP (전체 바인딩)
listening-ip=0.0.0.0

# 사용자 인증
user=${TURN_USERNAME}:${TURN_PASSWORD}

# 로그 설정
log-file=/var/log/turnserver.log
verbose

# 보안 설정
no-cli
no-tls
no-dtls
no-stdout-log

# Realm
realm=pnt-turn-server

# 최대 세션 수
max-bps=1000000
total-quota=100
user-quota=12

# ICE 지원
fingerprint
lt-cred-mech
EOF

echo "✅ TURN 서버 설정 파일 생성 완료: $TURN_CONFIG"

# 3. Coturn 서비스 활성화
echo "→ Coturn 서비스 활성화 중..."
if command -v systemctl >/dev/null 2>&1 && [ -d /run/systemd/system ]; then
  systemctl enable coturn
  systemctl restart coturn
else
  echo "⚠️  systemd가 없어서 turnserver를 직접 실행합니다."
  # -o: daemonize, -c: config
  turnserver -c "$TURN_CONFIG" -o
fi

# 4. 방화벽 포트 열기 (ufw 사용 시)
if command -v ufw &> /dev/null; then
  echo "→ 방화벽 포트 열기 중..."
  ufw allow 3478/udp
  ufw allow 3478/tcp
  ufw allow 49152:65535/udp  # RTP/RTCP 포트 범위
fi

# 5. 서비스 상태 확인
echo "→ Coturn 서비스 상태 확인 중..."
if command -v systemctl >/dev/null 2>&1 && [ -d /run/systemd/system ]; then
  if systemctl is-active --quiet coturn; then
    echo "✅ Coturn 서비스가 실행 중입니다"
  else
    echo "❌ Coturn 서비스 시작 실패"
    systemctl status coturn
    exit 1
  fi
else
  if pgrep -x turnserver >/dev/null 2>&1; then
    echo "✅ turnserver 프로세스가 실행 중입니다"
  else
    echo "❌ turnserver 프로세스 시작 실패"
    exit 1
  fi
fi

# 6. TURN 서버 정보 출력
PUBLIC_IP=$(curl -s ifconfig.me || curl -s ipinfo.io/ip || echo "YOUR_PUBLIC_IP")
echo ""
echo "=========================================="
echo "✅ TURN 서버 설정 완료!"
echo "=========================================="
echo "TURN URL: turn:${PUBLIC_IP}:3478"
echo "TURN URL (TLS): turns:${PUBLIC_IP}:5349"
echo "Username: ${TURN_USERNAME}"
echo "Password: ${TURN_PASSWORD}"
echo ""
echo "⚠️  중요:"
echo "1. external-ip를 서버의 실제 공인 IP로 변경하세요:"
echo "   nano $TURN_CONFIG"
echo "   external-ip=YOUR_PUBLIC_IP"
echo ""
echo "2. 클라이언트 앱에 다음 정보를 설정하세요:"
echo "   TURN_URL=turn:${PUBLIC_IP}:3478"
echo "   TURN_USERNAME=${TURN_USERNAME}"
echo "   TURN_CREDENTIAL=${TURN_PASSWORD}"
echo ""
echo "3. 설정 변경 후 Coturn 재시작:"
echo "   systemctl restart coturn"
echo "=========================================="
